### ISSUE TITLE
supports qb-shops ?

### ISSUE THREAD

**Issue by watchakorn-18k** [AxisGe0/axfw-inventory#4]
Does it support qb-shops?

**Comment by Rykamishlava** [comment]
No

**Comment by OBGMixer** [comment]
no and yes 

qb-shops uses
TriggerServerEvent("inventory:server:OpenInventory", "trunk", CurrentVehicle, other)

the inventory uses
TriggerServerEvent('ax-inv:Server:OpenInventory','Trunk-'..plate,{slots=20})

so it needs a custom qb-shops the qbcore-framework one doesnt work

**Comment by OBGMixer** [comment]
> Does it support qb-shops?

imma make a qb-shops that goes with the inventory

**Comment by NeonLifeRPde** [comment]
you done?
